# Generated by Django 2.2.1 on 2019-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='busy',
            field=models.CharField(default='', max_length=20),
        ),
    ]
