# Generated by Django 2.2.1 on 2019-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190511_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='busy',
            field=models.CharField(choices=[('매우 혼잡', '매우 혼잡'), ('혼잡', '혼잡'), ('보통', '보통'), ('여유', '여유')], max_length=20),
        ),
    ]
